### ISSUE TITLE
Receipts: Sletting bør kun gjøres via POST

### ISSUE THREAD

**Issue by kristandre** [vektorprogrammet/vektorprogrammet#567]
https://github.com/vektorprogrammet/vektorprogrammet/blob/receits/app/config/routing.yml#L613
```
receipt_delete:
  path: /utlegg/slett/{receipt}
  defaults: { _controller: AppBundle:Receipt:delete }
  methods: [GET]   <------- Bør være [POST]
  requirements:
    receipt: \d+
```

Sletting via GET betyr at et kvittering kan slettes bare ved å gå til en link (noen kan sende en malicious link, eller brukeren rett og slett går til den på egen hånd med tilbake-knapp, historie e.l.)

Eksempel på alternativ løsning: https://github.com/vektorprogrammet/vektorprogrammet/blob/master/app/Resources/views/substitute/index.html.twig#L109
